kind = "mobile"
previewPath = "/notes-mobile/"
title = "Scratch Pad Mobile"
version = "1.0.0"
id = "artifacts/notes-mobile"
router = "expo-domain"

[[services]]
name = "expo"
ensurePreviewReachable = "/status"
paths = [ "/notes-mobile/" ]
localPort = 21249

[services.development]
run = "pnpm --filter @workspace/notes-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/notes-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/notes-mobile", "run", "serve" ]

[services.env]
PORT = "21249"
BASE_PATH = "/notes-mobile/"
