/**
 * Zod schemas for the notifications API.
 *
 * Kept local to the api-server (not in @workspace/api-zod) because these
 * routes are hand-written, not generated by orval from the OpenAPI spec.
 */
import { z } from "zod/v4";

// ─── Shared ───────────────────────────────────────────────────────────────────

export const NotificationTypeEnum = z.enum([
  "task_assigned",
  "task_updated",
  "comment_added",
  "sla_breached",
  "mention",
  "comment_reply",
]);
export type NotificationType = z.infer<typeof NotificationTypeEnum>;

export const NotificationSchema = z.object({
  id: z.number(),
  orgId: z.string(),
  userId: z.string(),
  actorId: z.string().nullable(),
  actorName: z.string().nullable(),
  type: NotificationTypeEnum,
  entityType: z.string(),
  entityId: z.number(),
  message: z.string(),
  read: z.boolean(),
  createdAt: z.string(),
});

// ─── GET /notifications ───────────────────────────────────────────────────────

export const ListNotificationsQueryParams = z.object({
  limit: z.coerce.number().min(1).max(100).optional().default(50),
  offset: z.coerce.number().min(0).optional().default(0),
  unreadOnly: z.coerce.boolean().optional().default(false),
});

export const ListNotificationsResponse = z.object({
  notifications: z.array(NotificationSchema),
  unreadCount: z.number(),
  total: z.number(),
});

// ─── POST /notifications/read-all ─────────────────────────────────────────────

export const MarkAllReadResponse = z.object({ updated: z.number() });

// ─── PATCH /notifications/:id/read ────────────────────────────────────────────

export const MarkNotificationReadParams = z.object({
  id: z.coerce.number(),
});
export const MarkNotificationReadResponse = NotificationSchema;

// ─── DELETE /notifications/:id ────────────────────────────────────────────────

export const DeleteNotificationParams = z.object({
  id: z.coerce.number(),
});

// ─── GET /notification-preferences ───────────────────────────────────────────

export const NotificationPreferenceSchema = z.object({
  eventType: NotificationTypeEnum,
  enabled: z.boolean(),
});

export const GetNotificationPreferencesResponse = z.array(
  NotificationPreferenceSchema,
);

// ─── PATCH /notification-preferences ─────────────────────────────────────────

export const UpdateNotificationPreferencesBody = z.array(
  NotificationPreferenceSchema,
);
export const UpdateNotificationPreferencesResponse = z.array(
  NotificationPreferenceSchema,
);
