import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import orgsRouter from "./orgs";
import rolesRouter from "./roles";
import projectsRouter from "./projects";
import tasksRouter from "./tasks";
import commentsRouter from "./comments";
import notesRouter from "./notes";
import dashboardRouter from "./dashboard";
import docsRouter from "./docs";
import webhooksRouter from "./webhooks";
import customFieldsRouter from "./custom-fields";
import savedViewsRouter from "./saved-views";
import taskTemplatesRouter from "./task-templates";
import eventsRouter from "./events";
import workflowStagesRouter from "./workflow-stages";
import notificationsRouter from "./notifications";
import searchRouter from "./search";
import apiKeysRouter from "./api-keys";
import exportRouter from "./export";
import adminRouter from "./admin";
import unsubscribeRouter from "./unsubscribe";
import auditLogRouter from "./audit-log";
import referencesRouter from "./references";
import taskDependenciesRouter from "./task-dependencies";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(orgsRouter);
router.use(rolesRouter);
router.use(projectsRouter);
router.use(tasksRouter);
router.use(commentsRouter);
router.use(notesRouter);
router.use(dashboardRouter);
router.use(docsRouter);
router.use(webhooksRouter);
router.use(customFieldsRouter);
router.use(savedViewsRouter);
router.use(taskTemplatesRouter);
router.use(eventsRouter);
router.use(workflowStagesRouter);
router.use(notificationsRouter);
router.use(searchRouter);
router.use(apiKeysRouter);
router.use(exportRouter);
router.use(adminRouter);
router.use(unsubscribeRouter);
router.use(auditLogRouter);
router.use(referencesRouter);
router.use(taskDependenciesRouter);

export default router;
