// ─── Term key constants ───────────────────────────────────────────────────────
// These are kept here (not generated by orval) so the api-server can import
// them as a validated enum without pulling in the full generated client.
//
// The corresponding zod schemas (OrgTerminologyMap / GetOrgTerminologyResponse /
// PatchOrgTerminologyBody / PatchOrgTerminologyResponse) are now generated by
// orval from the OpenAPI spec and exported from ./generated/api.

export const TERMINOLOGY_KEYS = [
  'projects',
  'tasks',
  'members',
  'workflows',
  'stages',
] as const;

export type TerminologyKey = (typeof TERMINOLOGY_KEYS)[number];
