// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard-variants/CalmFeed.tsx": () => import("../components/mockups/dashboard-variants/CalmFeed.tsx"),
  "./components/mockups/dashboard-variants/MissionControl.tsx": () => import("../components/mockups/dashboard-variants/MissionControl.tsx"),
  "./components/mockups/dashboard-variants/WarmWorkspace.tsx": () => import("../components/mockups/dashboard-variants/WarmWorkspace.tsx")
};
